version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PAYMENT_BASE_URL=${PAYMENT_BASE_URL}
      - PAYMENT_PRIVATE_TOKEN=${PAYMENT_PRIVATE_TOKEN}
      - PAYMENT_PUBLIC_TOKEN=${PAYMENT_PUBLIC_TOKEN}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:11
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smallBus"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 7000:5432
    environment:
      POSTGRES_DB: "smallBus"
      POSTGRES_USER: "smallBus"
      POSTGRES_PASSWORD: "smallBus"
    volumes:
      - ./datapg:/var/lib/postgresql/data